[tool.poetry]
name = "seguid"
version = "0.0.2"
description = "Python implementation of SEGUID checksums for biological sequences"
authors = ["BjornFJohansson <bjornjobb@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8, <4.0"
pydivsufsort = { version = "^0.0.14", optional = true }

[tool.poetry.extras]
pydivsufsort =  ["pydivsufsort"]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
